services:

  db:
    image: mysql:8

    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: habit_shaper

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend

    ports:
      - "3000:3000"

    depends_on:
      - db

    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: habit_shaper
      JWT_SECRET: secretkey

    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend

    ports:
      - "5173:5173"

    depends_on:
      - backend

    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mysql_data: